modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT"

[[mods]]
  modId="slurpreborn"
  displayName="Slurp Reborn"
  description="Drink water with hands. Tough As Nails addon."
  version="${version}"
  displayURL="https://github.com/wendall911/SlurpReborn"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/SlurpReborn/1.18.x/files/updates.json"
  authors="wendall911"
  credits="ashar42"
  logoFile="assets/slurpreborn/textures/gui/logo.png"

[[dependencies.slurpreborn]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.slurpreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.slurpreborn]]
    modId="toughasnails"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
